name: lint json files with `jq`
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint-json:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - uses: cashapp/activate-hermit@v1
        name: setup hermit with `just` and `jq`
        with:
          cache: true

      - name: lint json files
        id: lint-json
        run: |
          just lint || echo "::set-output name=lint_failed::true"

      - name: add a comment to the pull request
        if: steps.lint.outputs.lint_failed == "true"
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "[error] linting failed. please fix the errors and push again."
            })
